#!/bin/bash

rm ../examples/res.txt
for net in {1..3}
do
	echo Evaluating network net${net}...
	for spec in `ls ../examples/net${net}/`
	do
		echo ${spec}
		res=$(python verifier.py --net net${net} --spec ../examples/net${net}/${spec})
		echo net${k}_${net},$spec,$res >> ../examples/res.txt
	done
done
